avatar_selection.settings:
  type: mapping
  label: Settings
  mapping:
    avatar_selection_disable_user_upload:
      type: boolean
    avatar_selection_force_user_avatar_reg:
      type: boolean
    avatar_selection_avatar_per_page:
      type: integer
    avatar_selection_force_user_avatar:
      type: boolean
    avatar_selection_set_random_default:
      type: boolean
    avatar_selection_distinctive_avatars:
      type: boolean
    avatar_selection_imagecache_preset:
      type: string
